# Generated by Django 4.0.5 on 2022-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalPart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/1/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/10/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/11/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/12/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/2/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/3/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/4/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/5/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/6/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/7/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/8/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticalPart9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/9/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WrittenPart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='written/1/')),
                ('ex1', models.TextField()),
                ('ex2', models.TextField()),
                ('ex3', models.TextField()),
                ('ex4', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WrittenPart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='written/2/')),
                ('ex1', models.TextField()),
                ('ex2', models.TextField()),
                ('ex3', models.TextField()),
                ('ex4', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WrittenPart3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='written/3/')),
                ('ex1', models.TextField()),
                ('ex2', models.TextField()),
                ('ex3', models.TextField()),
                ('ex4', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WrittenPart4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='written/4/')),
                ('ex1', models.TextField()),
                ('ex2', models.TextField()),
                ('ex3', models.TextField()),
                ('ex4', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WrittenPart5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='written/5/')),
                ('ex1', models.TextField()),
                ('ex2', models.TextField()),
                ('ex3', models.TextField()),
                ('ex4', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
