# Generated by Django 4.0.5 on 2022-06-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='practice/1/')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WrittenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('question', models.TextField()),
                ('example', models.ImageField(blank=True, upload_to='written/5/')),
                ('ex1', models.TextField()),
                ('ex2', models.TextField()),
                ('ex3', models.TextField()),
                ('ex4', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PracticalPart1',
        ),
        migrations.DeleteModel(
            name='PracticalPart10',
        ),
        migrations.DeleteModel(
            name='PracticalPart11',
        ),
        migrations.DeleteModel(
            name='PracticalPart12',
        ),
        migrations.DeleteModel(
            name='PracticalPart2',
        ),
        migrations.DeleteModel(
            name='PracticalPart3',
        ),
        migrations.DeleteModel(
            name='PracticalPart4',
        ),
        migrations.DeleteModel(
            name='PracticalPart5',
        ),
        migrations.DeleteModel(
            name='PracticalPart6',
        ),
        migrations.DeleteModel(
            name='PracticalPart7',
        ),
        migrations.DeleteModel(
            name='PracticalPart8',
        ),
        migrations.DeleteModel(
            name='PracticalPart9',
        ),
        migrations.DeleteModel(
            name='WrittenPart1',
        ),
        migrations.DeleteModel(
            name='WrittenPart2',
        ),
        migrations.DeleteModel(
            name='WrittenPart3',
        ),
        migrations.DeleteModel(
            name='WrittenPart4',
        ),
        migrations.DeleteModel(
            name='WrittenPart5',
        ),
    ]
