# Generated by Django 4.0.5 on 2022-06-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_practicalquestion_writtenquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenquestion',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
