# Generated by Django 4.0.5 on 2022-06-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_question_delete_practicalquestion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Problem',
        ),
    ]
