# Generated by Django 4.0.5 on 2022-06-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_rename_question_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ex1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ex2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ex3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ex4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='example',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.CharField>/<django.db.models.fields.IntegerField>/'),
        ),
    ]
