# Generated by Django 4.0.5 on 2022-06-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_problem_answer_alter_problem_ex1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
