# Generated by Django 4.0.5 on 2022-06-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_problem_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='ex1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ex2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ex3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ex4',
            field=models.IntegerField(blank=True),
        ),
    ]
