# Generated by Django 4.0.5 on 2022-06-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_problem_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='example',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.IntegerField>/<django.db.models.fields.IntegerField>/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.IntegerField(),
        ),
    ]
