# Generated by Django 4.0.5 on 2022-06-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_problem_example_alter_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='type_integer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='example',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/<django.db.models.fields.IntegerField>/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
