# Generated by Django 4.0.5 on 2022-07-04 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_problem_type_integer_alter_problem_example_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.problem')),
            ],
        ),
    ]
