# Generated by Django 4.0.5 on 2022-07-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_answer_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='comment',
        ),
    ]
