# Generated by Django 4.0.5 on 2022-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_remove_problem_answer_remove_problem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer_Problem',
        ),
    ]
