# Generated by Django 4.0.5 on 2022-07-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_problem_comment_img_alter_problem_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='type',
        ),
        migrations.AlterField(
            model_name='problem',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to="problem/<class 'type'>/<django.db.models.fields.IntegerField>/<django.db.models.fields.TextField>"),
        ),
        migrations.AlterField(
            model_name='problem',
            name='example',
            field=models.ImageField(blank=True, null=True, upload_to="problem/<class 'type'>/<django.db.models.fields.IntegerField>/<django.db.models.fields.TextField>"),
        ),
    ]
