# Generated by Django 4.0.5 on 2022-07-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_remove_problem_type_alter_problem_comment_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to='problem/<django.db.models.fields.IntegerField>/<django.db.models.fields.IntegerField>/<django.db.models.fields.TextField>'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='example',
            field=models.ImageField(blank=True, null=True, upload_to='problem/<django.db.models.fields.IntegerField>/<django.db.models.fields.IntegerField>/<django.db.models.fields.TextField>'),
        ),
    ]
