# Generated by Django 4.0.5 on 2022-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_bookreview_content_bookreview_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
