# Generated by Django 4.0.5 on 2022-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_book_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cnt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='stat_avg',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='stat_sum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
