# Generated by Django 4.0.5 on 2022-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_book_cnt_alter_book_stat_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(upload_to='board/bookcover/'),
        ),
    ]
